**Pandas** - Python Library that habdles the data in the form of tables, built on the top of numpy

**Features Of Pandas** -
1. Dataframes (2-d Array)
2. series (1-d Arrays)
3. handles almost all types of files
4. Data Cleaning
5. Aggregation


**Pandas Series** pandas series is a 1-d laeled array that can holds any type of data (Hetrogeneous Data)

In [1]:
import pandas as pd
# s = pd.Series(data,index = index) here data can be a list dict tuple numpy array
s = pd.Series([14,24,34,54,44])
print(s)

names = pd.Series([20,30,40,50], index = ["mukul","neelam", "rajveer", "neeraj"])
print(names)

data = {"Amit": 85, "Priya": 90, "Rahul": 78, "Sneha": 92}
marks = pd.Series(data)
print(marks)

0    14
1    24
2    34
3    54
4    44
dtype: int64
mukul      20
neelam     30
rajveer    40
neeraj     50
dtype: int64
Amit     85
Priya    90
Rahul    78
Sneha    92
dtype: int64

In [2]:
print(names['mukul'])
print(names[["mukul","neelam"]])

20
mukul     20
neelam    30
dtype: int64

**pandas Vectorized operations**  -- no need to iterate over a loop pandas apply it to every element autometically

In [3]:
print(s.mean())
print(s.min())
print(s.max())
print(s.sum())
print(s>30)
print(s.diff())

34.0
14
54
170
0    False
1    False
2     True
3     True
4     True
dtype: bool
0     NaN
1    10.0
2    10.0
3    20.0
4   -10.0
dtype: float64

**Series "name" attribute** -- it is useful when we combine the multiple series into a dataframe, each series become column and name become the column header

In [4]:
marks = pd.Series([10,20,30,40], name ="Marks")
names = pd.Series(["mukul","neelam","rajveer","neeraj"], name="Students Name")
df1 = pd.concat([marks,names], axis=1)
print(df1)

   Marks Students Name
0     10         mukul
1     20        neelam
2     30       rajveer
3     40        neeraj

**Dataframe** -- Dataframe is a 2-D array/table or a collection of series, each column is a seriesand all series share the same index

In [5]:
marks = pd.Series([10,20,30,40,50], index=[1,2,3,4,6])
subs = pd.Series([11,12,13,14,15], index=['a','b','c','d','e'])
df2 = pd.concat([marks,subs], axis=1)
print(df2)
## because are indexes are different

      0     1
1  10.0   NaN
2  20.0   NaN
3  30.0   NaN
4  40.0   NaN
6  50.0   NaN
a   NaN  11.0
b   NaN  12.0
c   NaN  13.0
d   NaN  14.0
e   NaN  15.0

In [6]:
marks = pd.Series([10,20,30,40,50], index=[1,2,3,4,6],name='marks')
subs = pd.Series([11,12,13,14,15], index=[1,2,3,4,6], name="sunject")
df2 = pd.concat([marks,subs], axis=1)
print(df2)

   marks  sunject
1     10       11
2     20       12
3     30       13
4     40       14
6     50       15

In [7]:
data = [
    {"Name": "Amit",  "Age": 20, "Marks": 85},
    {"Name": "Priya", "Age": 21, "Marks": 90},
    {"Name": "Rahul", "Age": 19, "Marks": 78},
]

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   Amit   20     85
1  Priya   21     90
2  Rahul   19     78

In [8]:
data = {
    "Marks": [85, 90, 78, 92],
    "City":  ["Delhi", "Mumbai", "Jaipur", "Pune"]
}

df = pd.DataFrame(data, index=["Amit", "Priya", "Rahul", "Sneha"])
print(df)

       Marks    City
Amit      85   Delhi
Priya     90  Mumbai
Rahul     78  Jaipur
Sneha     92    Pune

In [9]:
print(df.shape)      # (rows, columns)
print(df.columns)    # Column names
print(df.index)      # Row index
print(df.dtypes)     # Data type of each column
print(df.size)

(4, 2)
Index(['Marks', 'City'], dtype='object')
Index(['Amit', 'Priya', 'Rahul', 'Sneha'], dtype='object')
Marks     int64
City     object
dtype: object
8

single brackets return the series

In [10]:
df3 = df2["marks"]
print(type(df3))

<class 'pandas.core.series.Series'>

double brackets return dataframe

In [11]:
df4 = df2[["marks"]]
print(type(df4))

<class 'pandas.core.frame.DataFrame'>

**Accessing in pandas dataframes**
1. df["col"] -- it returns a column
2. df.loc[] --- labeled based (names of row/columns)
3. df.iloc[] --- position based (position of row/column)

In [12]:
data = {
    "name": ['a','b','c','d','e'],
    "marks" : [10,20,30,40,50],
   "grade" : [1,2,3,4,5],
    "result" : ['p','f','f','p','p']

}
df =pd.DataFrame(data)
print(df)

  name  marks  grade result
0    a     10      1      p
1    b     20      2      f
2    c     30      3      f
3    d     40      4      p
4    e     50      5      p

In [13]:
df.shape

(5, 4)

In [14]:
print(df["marks"])
print(df[["marks","grade"]])

0    10
1    20
2    30
3    40
4    50
Name: marks, dtype: int64
   marks  grade
0     10      1
1     20      2
2     30      3
3     40      4
4     50      5

In [15]:
print(df.loc[0],end='\n \n')
print(df.loc[0:2],end='\n\n')
print(df.loc[0,"name"],end='\n\n')
print(df.loc[0:3, "name": "grade"])

name       a
marks     10
grade      1
result     p
Name: 0, dtype: object

  name  marks  grade result
0    a     10      1      p
1    b     20      2      f
2    c     30      3      f

a

  name  marks  grade
0    a     10      1
1    b     20      2
2    c     30      3
3    d     40      4

In [16]:
print(df.iloc[0])
print(df.iloc[0:2])
print(df.iloc[0,2])
print(df.iloc[0:2,1:4])

name       a
marks     10
grade      1
result     p
Name: 0, dtype: object
  name  marks  grade result
0    a     10      1      p
1    b     20      2      f
1
   marks  grade result
0     10      1      p
1     20      2      f

the main difference loc and iloc is that loc is labeled based and end inclusive and ilocis no based and end exclusive

In [17]:
data = {
    'Name':   ['Alia', 'Rohit', 'Sara', 'Karan', 'Priya'],
    'City':   ['Delhi', 'Mumbai', 'Jaipur', 'Chennai', 'Delhi'],
    'Score':  [85, 92, 78, 95, 88],
    'Age':    [22, 25, 21, 27, 23]
}

df = pd.DataFrame(data)

**Filtering in pandas**

In [18]:
# find studens whose score >85
print(df["Score"]>85) # returns the series of true and false (Boolean Series)
df1=pd.DataFrame(df["Score"]>85) # return the dataframe of boolean series

print(df1)
df2=df[df["Score"]>85] # uses boolean series as filter and return where condition is true
df2

0    False
1     True
2    False
3     True
4     True
Name: Score, dtype: bool
   Score
0  False
1   True
2  False
3   True
4   True

    Name     City  Score  Age
1  Rohit   Mumbai     92   25
3  Karan  Chennai     95   27
4  Priya    Delhi     88   23

In [19]:
#multiple conditions
df3 = df[(df['Score'] > 80) & (df['Age'] < 25)]
print(df3)

df3 = df[(df['Score'] > 80) | (df['Age'] < 25)]
print(df3)

df[(df['City'] == 'Delhi')]

    Name   City  Score  Age
0   Alia  Delhi     85   22
4  Priya  Delhi     88   23
    Name     City  Score  Age
0   Alia    Delhi     85   22
1  Rohit   Mumbai     92   25
2   Sara   Jaipur     78   21
3  Karan  Chennai     95   27
4  Priya    Delhi     88   23

    Name   City  Score  Age
0   Alia  Delhi     85   22
4  Priya  Delhi     88   23

In [20]:
print(df[df['City'].isin(['Delhi', 'Mumbai'])])
print(df[df['Score'].between(80, 90)])

    Name    City  Score  Age
0   Alia   Delhi     85   22
1  Rohit  Mumbai     92   25
4  Priya   Delhi     88   23
    Name   City  Score  Age
0   Alia  Delhi     85   22
4  Priya  Delhi     88   23

**Adding new columns to df**

In [21]:
df["result"]=['T','T','F','T','F']
print(df)

    Name     City  Score  Age result
0   Alia    Delhi     85   22      T
1  Rohit   Mumbai     92   25      T
2   Sara   Jaipur     78   21      F
3  Karan  Chennai     95   27      T
4  Priya    Delhi     88   23      F

**Inserting Column at a specificposition**

In [22]:
df.insert(2,"present",['p','a','a','p','a'])
print(df)

    Name     City present  Score  Age result
0   Alia    Delhi       p     85   22      T
1  Rohit   Mumbai       a     92   25      T
2   Sara   Jaipur       a     78   21      F
3  Karan  Chennai       p     95   27      T
4  Priya    Delhi       a     88   23      F

** deleting droping a column**

In [23]:
df.drop('present',axis=1,inplace=True)
print(df)

    Name     City  Score  Age result
0   Alia    Delhi     85   22      T
1  Rohit   Mumbai     92   25      T
2   Sara   Jaipur     78   21      F
3  Karan  Chennai     95   27      T
4  Priya    Delhi     88   23      F

1. if axis=1 column is deleted
2. if axis =0 row is deleted

In [24]:
df.drop([0,2],axis=0,inplace=True)
print(df)

    Name     City  Score  Age result
1  Rohit   Mumbai     92   25      T
3  Karan  Chennai     95   27      T
4  Priya    Delhi     88   23      F

**Renaming of column**

In [25]:
df.rename(columns={'Name':"student"}, inplace = True)

In [26]:
df

  student     City  Score  Age result
1   Rohit   Mumbai     92   25      T
3   Karan  Chennai     95   27      T
4   Priya    Delhi     88   23      F

**Missing Values**

In [27]:

import numpy as np
data = {
    'Name':   ['Amit', 'Neha', 'Raj', 'Pooja', 'Karan'],
    'Age':    [22, None, 25, np.nan, 28],
    'Score':  [85, 92, np.nan, 95, None],
    'City':   ['Delhi', 'Mumbai', None, 'Chennai', 'Pune']
}

df = pd.DataFrame(data)
print(df)

    Name   Age  Score     City
0   Amit  22.0   85.0    Delhi
1   Neha   NaN   92.0   Mumbai
2    Raj  25.0    NaN     None
3  Pooja   NaN   95.0  Chennai
4  Karan  28.0    NaN     Pune

In [28]:
print(df.isnull())
print(df.isna().sum())
print(df.isnull().sum() / len(df) * 100)
print(df.isnull().any())

    Name    Age  Score   City
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False   True  False  False
4  False  False   True  False
Name     0
Age      2
Score    2
City     1
dtype: int64
Name      0.0
Age      40.0
Score    40.0
City     20.0
dtype: float64
Name     False
Age       True
Score     True
City      True
dtype: bool

In [29]:
df.dropna(subset=['Score', 'Age'])

   Name   Age  Score   City
0  Amit  22.0   85.0  Delhi

In [30]:
df.dropna()

   Name   Age  Score   City
0  Amit  22.0   85.0  Delhi

In [31]:
df.dropna(axis=1) # column delete

    Name
0   Amit
1   Neha
2    Raj
3  Pooja
4  Karan

In [32]:
df.fillna(0)                    # Sab NaN ko 0 se replace karo
df['Score'].fillna(0)           # Sirf Score column ka NaN
df.fillna({'Age': 0, 'City': 'Unknown'})  # Alag-alag columns ke liye alag values

    Name   Age  Score     City
0   Amit  22.0   85.0    Delhi
1   Neha   0.0   92.0   Mumbai
2    Raj  25.0    NaN  Unknown
3  Pooja   0.0   95.0  Chennai
4  Karan  28.0    NaN     Pune

**File Reading**
1. pd.read_csv("data.csv") --- read complete csv file
2. pd.read_csv("data.csv",sep=';') --- sep used when file is saperated by other delimiter instead of comma
3. pd.read_csv("data.csv", names=["name","age","marks"]) --- it gives the specific names to the file columns
4. pd.read_csv("data.csv", nrows=100) --- select the top 100 rows in data
5. pd.read_csv("data.csv", usecols=["name","marks"]) --- select specific columns from complete data file

1. df.read_excel("data.xlsx")
2. df.read_excel("data.xlsx", sheet_name="sheet2")

3. df.read_json("data.json")

In [34]:
df = pd.read_csv("data.csv", nrows = 300)
print(df.shape)

(300, 9)

In [35]:
df=pd.read_csv("data.csv", usecols=["BMI","Age"])
df.head()

    BMI  Age
0  33.6   50
1  26.6   31
2  23.3   32
3  28.1   21
4  43.1   33

In [36]:
df=pd.read_csv("data.csv", usecols=[2,3])
df.head()

   BloodPressure  SkinThickness
0             72             35
1             66             29
2             64              0
3             66             23
4             40             35

In [37]:
df=pd.read_csv("data.csv", usecols=[2,3,4,7])
df.head()

   BloodPressure  SkinThickness  Insulin  Age
0             72             35        0   50
1             66             29        0   31
2             64              0        0   32
3             66             23       94   21
4             40             35      168   33

In [38]:
df = pd.read_csv("data.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

df.info() -- it gives the structural information about the dataframe like no of rows ans no of columns datatypes null values and memory uses

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               769 non-null    int64
 1   Glucose                   769 non-null    int64
 2   BloodPressure             769 non-null    int64
 3   SkinThickness             769 non-null    int64
 4   Insulin                   769 non-null    int64
 5   BMI                       769 non-null    float64
 6   DiabetesPedigreeFunction  769 non-null    float64
 7   Age                       769 non-null    int64
 8   Outcome                   769 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.2 KB

df.describe() -- it gives the statistcal information about the dataset like min max mean and quartiles

In [40]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000
mean,3.840052,120.897269,69.115735,20.509753,79.697009,31.998179,0.471590,33.269181,0.349805
std,3.370237,31.951886,19.345296,15.959020,115.203999,7.880557,0.331208,11.778737,0.477219
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,29.000000,32.000000,0.371000,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,127.000000,36.600000,0.626000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

1. df.value_counts() --- it counts the frequency of eachunique value
2. df.nunique() --- it count the unique value

In [41]:
print(df.value_counts())

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age  Outcome
17           163      72             41             114      40.9  0.817                     47   1          1
12           140      82             43             325      39.2  0.528                     58   1          1
             121      78             17             0        26.5  0.259                     62   0          1
             106      80             0              0        23.6  0.137                     44   0          1
             100      84             33             105      30.0  0.488                     46   0          1
                                                                                                            ..
0            84       64             22             66       35.8  0.545                     21   0          1
             78       88             29             40       36.9  0.434                     21   0          1
             74       52             10             36       27.8  0.269                     22   0          1
             73       0              0              0        21.1  0.342                     25   0          1
             67       76             0              0        45.3  0.194                     46   0          1
Name: count, Length: 769, dtype: int64

In [42]:
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                48
SkinThickness                51
Insulin                     187
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [43]:
print(df.tail())
print(df.index)
print(df.columns)
print(df.dtypes)
print(df["BMI"].dtypes)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4
768            0      123             77              0        1  36.3

     DiabetesPedigreeFunction  Age  Outcome
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0
768                     0.252   55        1
RangeIndex(start=0, stop=769, step=1)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object
float64

**Data Type Conversion**

In [44]:
df["Age"] = df["Age"].astype("string")
print(df["Age"].dtypes)

string

In [45]:
df["Age"] = df["Age"].astype(float)
print(df["Age"].dtypes)

float64

1. map() function is used in label encoding / category conversion / value replacement
2. apply(function,axis) it apply the function to all data row by row df['score'].apply(function)
3. lambda is a anonymous one line function lambda x : x*x

In [52]:
df = pd.DataFrame({
    "Gender":["M","F","M","F"]
})
print(df)
df['Gender']=df['Gender'].map({"M" :"Men","F" :"Female"})
df

  Gender
0      M
1      F
2      M
3      F

   Gender
0     Men
1  Female
2     Men
3  Female

In [54]:
df = pd.DataFrame({
    "Score":[80,90,70]
})
print(df)
def add_bonus(x):
    return x + 10
df["Score"] = df["Score"].apply(add_bonus)
df

   Score
0     80
1     90
2     70

   Score
0     90
1    100
2     80

In [56]:
df["Score"].apply(lambda x: x*x)
df

   Score
0     90
1    100
2     80

**Vectorization** --- Performing an operation on an entire Series/DataFrame at once instead of processing one row at a time.

In [57]:
df = pd.DataFrame({
    "Name":["A","B","C","D"],
    "Salary":[50000,60000,40000,55000]
})
print(df)

  Name  Salary
0    A   50000
1    B   60000
2    C   40000
3    D   55000

In [59]:
new_salary = [] #non-vectorized approach
for salary in df["Salary"]:
    new_salary.append(salary + 5000)
df["New_Salary"] = new_salary
df

  Name  Salary  New_Salary
0    A   50000       55000
1    B   60000       65000
2    C   40000       45000
3    D   55000       60000

In [61]:
df["New_Salary"] = df["Salary"] + 5000 # vectorized approach
df

  Name  Salary  New_Salary
0    A   50000       55000
1    B   60000       65000
2    C   40000       45000
3    D   55000       60000

**groupby()** splits data into groups based on a column and then performs calculations on each group.

In [62]:
df = pd.DataFrame({
    "Department":["IT","IT","HR","HR","Sales"],
    "Employee":["A","B","C","D","E"],
    "Salary":[50000,70000,40000,60000,55000]
})

df

  Department Employee  Salary
0         IT        A   50000
1         IT        B   70000
2         HR        C   40000
3         HR        D   60000
4      Sales        E   55000

In [63]:
df.groupby("Department")["Salary"].mean()

Department
HR       50000.0
IT       60000.0
Sales    55000.0
Name: Salary, dtype: float64

at first it group the data by department and them apply mean on it

In [64]:
df.groupby("Department")["Salary"].sum()

Department
HR       100000
IT       120000
Sales     55000
Name: Salary, dtype: int64

In [65]:
df.groupby("Department")["Salary"].agg(["mean","sum","max","min","count"])

               mean     sum    max    min  count
Department
HR          50000.0  100000  60000  40000      2
IT          60000.0  120000  70000  50000      2
Sales       55000.0   55000  55000  55000      1

In [66]:
df = pd.DataFrame({
    "Department":["IT","IT","HR","HR"],
    "Gender":["M","F","M","F"],
    "Salary":[50000,70000,40000,60000]
})

In [67]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)

             Salary
Department
HR          50000.0
IT          60000.0

A Pivot Table is a tool used to summarize and aggregate data by grouping rows and columns and applying calculations such as:,Sum,Mean,Count,Min,Max
It helps convert detailed data into a summary report.

In [68]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

Gender            F        M
Department
HR          60000.0  40000.0
IT          70000.0  50000.0

In [69]:
df = pd.DataFrame({
    "Gender":["M","F","M","F","M"],
    "Department":["IT","IT","HR","HR","IT"]
})

A Crosstab (Cross Tabulation) is used to calculate the frequency (count) of combinations between two or more categorical variables.

In [70]:
pd.crosstab(
    df["Gender"],
    df["Department"]
)

Department  HR  IT
Gender
F            1   1
M            1   2

In [72]:

df1 = pd.DataFrame({
    "Name":["A","B"]
})

df2 = pd.DataFrame({
    "Name":["C","D"]
})

df = pd.concat([df1,df2])
df =df.reset_index(drop=False)
df

   index Name
0      0    A
1      1    B
2      0    C
3      1    D

In [73]:
pd.concat([df1,df2],ignore_index=True)
df

   index Name
0      0    A
1      1    B
2      0    C
3      1    D

In [74]:
pd.concat( [df1,df2], axis=1)

  Name Name
0    A    C
1    B    D

**Multiindex** more than one index in dataframe
To represent hierarchical or multi-level data efficiently.

In [76]:
df = pd.DataFrame({
    "Department":["IT","IT","HR"],
    "Employee":["A","B","C"],
    "Salary":[50000,60000,40000]
})

df = df.set_index(
    ["Department","Employee"]
)

print(df)

                     Salary
Department Employee
IT         A          50000
           B          60000
HR         C          40000